ui changes just that, and add some logic handle hehe
Signed-off-by: clyfly <deni@xyradcloud.my.id>

minor update
some changes on quoted text `task_listener`

Signed-off-by: clyfly <deni@xyradcloud.my.id>

 authorized_uset user need to join authorize chat first atleast 1 chat so they can access their user settings from bot pm

SyntaxError: f-string: expecting '}'

Signed-off-by: clyfly <deni@xyradcloud.my.id>

minor fix